name: Python application

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build & Push Image
      uses: docker/build-push-action@v1
      with:
        username: ${{DOCKER.USERNAME}}
        password: ${{DOCKER.PASSWORD}}
        repository: cj22011992 / demo-app
        tags: latest, ${{github.run_number}}
