name: Python application

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build & Push Image
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER.USERNAME }}
        password: ${{ secrets.DOCKER.PASSWORD }}
        repository: cj22011992 / demo-app
        tags: latest, ${{ github.run_number }}
